from datetime import datetime, timedelta

# Performance Data
employees = [
    {"id": 1, "name": "John Smith", "role": "Software Engineer", "score": 85, 
     "tasks_completed": 24, "tasks_in_progress": 3},
    {"id": 2, "name": "Emma Wilson", "role": "Data Analyst", "score": 92, 
     "tasks_completed": 18, "tasks_in_progress": 2},
    {"id": 3, "name": "Michael Chen", "role": "Product Manager", "score": 88, 
     "tasks_completed": 15, "tasks_in_progress": 4},
    {"id": 4, "name": "Sarah Davis", "role": "UX Designer", "score": 90, 
     "tasks_completed": 21, "tasks_in_progress": 2},
    {"id": 5, "name": "Alex Taylor", "role": "DevOps Engineer", "score": 87, 
     "tasks_completed": 19, "tasks_in_progress": 5},
    {"id": 6, "name": "Olivia Kim", "role": "Frontend Developer", "score": 91, 
     "tasks_completed": 22, "tasks_in_progress": 2},
    {"id": 7, "name": "David Park", "role": "Data Scientist", "score": 89, 
     "tasks_completed": 17, "tasks_in_progress": 3},
    {"id": 8, "name": "Maya Roberts", "role": "Backend Developer", "score": 86, 
     "tasks_completed": 20, "tasks_in_progress": 4},
]

# Collaboration Data by Month
collaboration_data = {'2014-11': [{'from': 'elendiastarman', 'to': 'seberg', 'count': 1}],
 '2015-04': [{'from': 'elendiastarman', 'to': 'seberg', 'count': 1},
  {'from': 'mhvk', 'to': 'pv', 'count': 2},
  {'from': 'mhvk', 'to': 'charris', 'count': 2},
  {'from': 'mhvk', 'to': 'njsmith', 'count': 2},
  {'from': 'njsmith', 'to': 'pv', 'count': 1},
  {'from': 'njsmith', 'to': 'charris', 'count': 1},
  {'from': 'njsmith', 'to': 'mhvk', 'count': 1}],
 '2015-05': [{'from': 'elendiastarman', 'to': 'seberg', 'count': 1},
  {'from': 'mhvk', 'to': 'pv', 'count': 3},
  {'from': 'mhvk', 'to': 'charris', 'count': 3},
  {'from': 'mhvk', 'to': 'njsmith', 'count': 3},
  {'from': 'njsmith', 'to': 'pv', 'count': 4},
  {'from': 'njsmith', 'to': 'charris', 'count': 4},
  {'from': 'njsmith', 'to': 'mhvk', 'count': 4},
  {'from': 'charris', 'to': 'pv', 'count': 5},
  {'from': 'charris', 'to': 'mhvk', 'count': 5},
  {'from': 'charris', 'to': 'njsmith', 'count': 5},
  {'from': 'pv', 'to': 'charris', 'count': 1},
  {'from': 'pv', 'to': 'mhvk', 'count': 1},
  {'from': 'pv', 'to': 'njsmith', 'count': 1}],
 '2016-02': [{'from': 'elendiastarman', 'to': 'seberg', 'count': 1},
  {'from': 'mhvk', 'to': 'pv', 'count': 3},
  {'from': 'mhvk', 'to': 'charris', 'count': 3},
  {'from': 'mhvk', 'to': 'njsmith', 'count': 3},
  {'from': 'njsmith', 'to': 'pv', 'count': 4},
  {'from': 'njsmith', 'to': 'charris', 'count': 4},
  {'from': 'njsmith', 'to': 'mhvk', 'count': 4},
  {'from': 'charris', 'to': 'pv', 'count': 5},
  {'from': 'charris', 'to': 'mhvk', 'count': 5},
  {'from': 'charris', 'to': 'njsmith', 'count': 5},
  {'from': 'pv', 'to': 'charris', 'count': 1},
  {'from': 'pv', 'to': 'mhvk', 'count': 1},
  {'from': 'pv', 'to': 'njsmith', 'count': 1},
  {'from': 'seberg', 'to': 'elendiastarman', 'count': 1}],
 '2017-02': [{'from': 'elendiastarman', 'to': 'seberg', 'count': 1},
  {'from': 'mhvk', 'to': 'pv', 'count': 3},
  {'from': 'mhvk', 'to': 'charris', 'count': 3},
  {'from': 'mhvk', 'to': 'njsmith', 'count': 3},
  {'from': 'njsmith', 'to': 'pv', 'count': 4},
  {'from': 'njsmith', 'to': 'charris', 'count': 4},
  {'from': 'njsmith', 'to': 'mhvk', 'count': 4},
  {'from': 'charris', 'to': 'pv', 'count': 5},
  {'from': 'charris', 'to': 'mhvk', 'count': 5},
  {'from': 'charris', 'to': 'njsmith', 'count': 5},
  {'from': 'pv', 'to': 'charris', 'count': 1},
  {'from': 'pv', 'to': 'mhvk', 'count': 1},
  {'from': 'pv', 'to': 'njsmith', 'count': 1},
  {'from': 'seberg', 'to': 'elendiastarman', 'count': 1},
  {'from': 'manuels', 'to': 'pv', 'count': 1},
  {'from': 'manuels', 'to': 'WarrenWeckesser', 'count': 1},
  {'from': 'pv', 'to': 'WarrenWeckesser', 'count': 1},
  {'from': 'pv', 'to': 'manuels', 'count': 1}],
 '2018-07': [{'from': 'elendiastarman', 'to': 'seberg', 'count': 1},
  {'from': 'mhvk', 'to': 'pv', 'count': 3},
  {'from': 'mhvk', 'to': 'charris', 'count': 3},
  {'from': 'mhvk', 'to': 'njsmith', 'count': 3},
  {'from': 'njsmith', 'to': 'pv', 'count': 4},
  {'from': 'njsmith', 'to': 'charris', 'count': 4},
  {'from': 'njsmith', 'to': 'mhvk', 'count': 4},
  {'from': 'charris', 'to': 'pv', 'count': 5},
  {'from': 'charris', 'to': 'mhvk', 'count': 5},
  {'from': 'charris', 'to': 'njsmith', 'count': 5},
  {'from': 'pv', 'to': 'charris', 'count': 1},
  {'from': 'pv', 'to': 'mhvk', 'count': 1},
  {'from': 'pv', 'to': 'njsmith', 'count': 1},
  {'from': 'seberg', 'to': 'elendiastarman', 'count': 1},
  {'from': 'manuels', 'to': 'pv', 'count': 1},
  {'from': 'manuels', 'to': 'WarrenWeckesser', 'count': 1},
  {'from': 'pv', 'to': 'WarrenWeckesser', 'count': 1},
  {'from': 'pv', 'to': 'manuels', 'count': 1},
  {'from': 'will133', 'to': 'charris', 'count': 2},
  {'from': 'charris', 'to': 'will133', 'count': 3}],
 '2018-09': [{'from': 'elendiastarman', 'to': 'seberg', 'count': 1},
  {'from': 'mhvk', 'to': 'pv', 'count': 3},
  {'from': 'mhvk', 'to': 'charris', 'count': 3},
  {'from': 'mhvk', 'to': 'njsmith', 'count': 3},
  {'from': 'njsmith', 'to': 'pv', 'count': 4},
  {'from': 'njsmith', 'to': 'charris', 'count': 4},
  {'from': 'njsmith', 'to': 'mhvk', 'count': 4},
  {'from': 'charris', 'to': 'pv', 'count': 5},
  {'from': 'charris', 'to': 'mhvk', 'count': 5},
  {'from': 'charris', 'to': 'njsmith', 'count': 5},
  {'from': 'pv', 'to': 'charris', 'count': 1},
  {'from': 'pv', 'to': 'mhvk', 'count': 1},
  {'from': 'pv', 'to': 'njsmith', 'count': 1},
  {'from': 'seberg', 'to': 'elendiastarman', 'count': 1},
  {'from': 'manuels', 'to': 'pv', 'count': 1},
  {'from': 'manuels', 'to': 'WarrenWeckesser', 'count': 1},
  {'from': 'pv', 'to': 'WarrenWeckesser', 'count': 1},
  {'from': 'pv', 'to': 'manuels', 'count': 1},
  {'from': 'will133', 'to': 'charris', 'count': 2},
  {'from': 'charris', 'to': 'will133', 'count': 3},
  {'from': 'hmaarrfk', 'to': 'charris', 'count': 2},
  {'from': 'hmaarrfk', 'to': 'eric-wieser', 'count': 2},
  {'from': 'eric-wieser', 'to': 'charris', 'count': 2},
  {'from': 'eric-wieser', 'to': 'hmaarrfk', 'count': 2},
  {'from': 'charris', 'to': 'hmaarrfk', 'count': 2},
  {'from': 'charris', 'to': 'eric-wieser', 'count': 2}],
 '2019-05': [{'from': 'elendiastarman', 'to': 'seberg', 'count': 1},
  {'from': 'mhvk', 'to': 'pv', 'count': 3},
  {'from': 'mhvk', 'to': 'charris', 'count': 3},
  {'from': 'mhvk', 'to': 'njsmith', 'count': 3},
  {'from': 'njsmith', 'to': 'pv', 'count': 4},
  {'from': 'njsmith', 'to': 'charris', 'count': 4},
  {'from': 'njsmith', 'to': 'mhvk', 'count': 4},
  {'from': 'charris', 'to': 'pv', 'count': 5},
  {'from': 'charris', 'to': 'mhvk', 'count': 5},
  {'from': 'charris', 'to': 'njsmith', 'count': 5},
  {'from': 'pv', 'to': 'charris', 'count': 1},
  {'from': 'pv', 'to': 'mhvk', 'count': 1},
  {'from': 'pv', 'to': 'njsmith', 'count': 1},
  {'from': 'seberg', 'to': 'elendiastarman', 'count': 1},
  {'from': 'manuels', 'to': 'pv', 'count': 1},
  {'from': 'manuels', 'to': 'WarrenWeckesser', 'count': 1},
  {'from': 'pv', 'to': 'WarrenWeckesser', 'count': 1},
  {'from': 'pv', 'to': 'manuels', 'count': 1},
  {'from': 'will133', 'to': 'charris', 'count': 2},
  {'from': 'charris', 'to': 'will133', 'count': 3},
  {'from': 'hmaarrfk', 'to': 'charris', 'count': 2},
  {'from': 'hmaarrfk', 'to': 'eric-wieser', 'count': 2},
  {'from': 'eric-wieser', 'to': 'charris', 'count': 2},
  {'from': 'eric-wieser', 'to': 'hmaarrfk', 'count': 2},
  {'from': 'charris', 'to': 'hmaarrfk', 'count': 3},
  {'from': 'charris', 'to': 'eric-wieser', 'count': 3}],
 '2021-09': [{'from': 'elendiastarman', 'to': 'seberg', 'count': 1},
  {'from': 'mhvk', 'to': 'pv', 'count': 3},
  {'from': 'mhvk', 'to': 'charris', 'count': 3},
  {'from': 'mhvk', 'to': 'njsmith', 'count': 3},
  {'from': 'njsmith', 'to': 'pv', 'count': 4},
  {'from': 'njsmith', 'to': 'charris', 'count': 4},
  {'from': 'njsmith', 'to': 'mhvk', 'count': 4},
  {'from': 'charris', 'to': 'pv', 'count': 5},
  {'from': 'charris', 'to': 'mhvk', 'count': 5},
  {'from': 'charris', 'to': 'njsmith', 'count': 5},
  {'from': 'pv', 'to': 'charris', 'count': 1},
  {'from': 'pv', 'to': 'mhvk', 'count': 1},
  {'from': 'pv', 'to': 'njsmith', 'count': 1},
  {'from': 'seberg', 'to': 'elendiastarman', 'count': 1},
  {'from': 'manuels', 'to': 'pv', 'count': 1},
  {'from': 'manuels', 'to': 'WarrenWeckesser', 'count': 1},
  {'from': 'pv', 'to': 'WarrenWeckesser', 'count': 1},
  {'from': 'pv', 'to': 'manuels', 'count': 1},
  {'from': 'will133', 'to': 'charris', 'count': 2},
  {'from': 'charris', 'to': 'will133', 'count': 3},
  {'from': 'hmaarrfk', 'to': 'charris', 'count': 2},
  {'from': 'hmaarrfk', 'to': 'eric-wieser', 'count': 2},
  {'from': 'eric-wieser', 'to': 'charris', 'count': 2},
  {'from': 'eric-wieser', 'to': 'hmaarrfk', 'count': 2},
  {'from': 'charris', 'to': 'hmaarrfk', 'count': 3},
  {'from': 'charris', 'to': 'eric-wieser', 'count': 3},
  {'from': 'Sharkoo123', 'to': 'charris', 'count': 3},
  {'from': 'Sharkoo123', 'to': 'seberg', 'count': 3},
  {'from': 'seberg', 'to': 'Sharkoo123', 'count': 2},
  {'from': 'seberg', 'to': 'charris', 'count': 2},
  {'from': 'charris', 'to': 'Sharkoo123', 'count': 1},
  {'from': 'charris', 'to': 'seberg', 'count': 1}],
 '2021-10': [{'from': 'elendiastarman', 'to': 'seberg', 'count': 1},
  {'from': 'mhvk', 'to': 'pv', 'count': 3},
  {'from': 'mhvk', 'to': 'charris', 'count': 3},
  {'from': 'mhvk', 'to': 'njsmith', 'count': 3},
  {'from': 'njsmith', 'to': 'pv', 'count': 4},
  {'from': 'njsmith', 'to': 'charris', 'count': 4},
  {'from': 'njsmith', 'to': 'mhvk', 'count': 4},
  {'from': 'charris', 'to': 'pv', 'count': 5},
  {'from': 'charris', 'to': 'mhvk', 'count': 5},
  {'from': 'charris', 'to': 'njsmith', 'count': 5},
  {'from': 'pv', 'to': 'charris', 'count': 1},
  {'from': 'pv', 'to': 'mhvk', 'count': 1},
  {'from': 'pv', 'to': 'njsmith', 'count': 1},
  {'from': 'seberg', 'to': 'elendiastarman', 'count': 1},
  {'from': 'manuels', 'to': 'pv', 'count': 1},
  {'from': 'manuels', 'to': 'WarrenWeckesser', 'count': 1},
  {'from': 'pv', 'to': 'WarrenWeckesser', 'count': 1},
  {'from': 'pv', 'to': 'manuels', 'count': 1},
  {'from': 'will133', 'to': 'charris', 'count': 2},
  {'from': 'charris', 'to': 'will133', 'count': 3},
  {'from': 'hmaarrfk', 'to': 'charris', 'count': 2},
  {'from': 'hmaarrfk', 'to': 'eric-wieser', 'count': 2},
  {'from': 'eric-wieser', 'to': 'charris', 'count': 2},
  {'from': 'eric-wieser', 'to': 'hmaarrfk', 'count': 2},
  {'from': 'charris', 'to': 'hmaarrfk', 'count': 3},
  {'from': 'charris', 'to': 'eric-wieser', 'count': 3},
  {'from': 'Sharkoo123', 'to': 'charris', 'count': 3},
  {'from': 'Sharkoo123', 'to': 'seberg', 'count': 3},
  {'from': 'seberg', 'to': 'Sharkoo123', 'count': 2},
  {'from': 'seberg', 'to': 'charris', 'count': 2},
  {'from': 'charris', 'to': 'Sharkoo123', 'count': 1},
  {'from': 'charris', 'to': 'seberg', 'count': 1},
  {'from': 'WarrenWeckesser', 'to': 'pv', 'count': 2},
  {'from': 'WarrenWeckesser', 'to': 'manuels', 'count': 2}],
 '2021-12': [{'from': 'elendiastarman', 'to': 'seberg', 'count': 1},
  {'from': 'mhvk', 'to': 'pv', 'count': 3},
  {'from': 'mhvk', 'to': 'charris', 'count': 3},
  {'from': 'mhvk', 'to': 'njsmith', 'count': 3},
  {'from': 'njsmith', 'to': 'pv', 'count': 4},
  {'from': 'njsmith', 'to': 'charris', 'count': 4},
  {'from': 'njsmith', 'to': 'mhvk', 'count': 4},
  {'from': 'charris', 'to': 'pv', 'count': 5},
  {'from': 'charris', 'to': 'mhvk', 'count': 5},
  {'from': 'charris', 'to': 'njsmith', 'count': 5},
  {'from': 'pv', 'to': 'charris', 'count': 1},
  {'from': 'pv', 'to': 'mhvk', 'count': 1},
  {'from': 'pv', 'to': 'njsmith', 'count': 1},
  {'from': 'seberg', 'to': 'elendiastarman', 'count': 1},
  {'from': 'manuels', 'to': 'pv', 'count': 1},
  {'from': 'manuels', 'to': 'WarrenWeckesser', 'count': 1},
  {'from': 'pv', 'to': 'WarrenWeckesser', 'count': 1},
  {'from': 'pv', 'to': 'manuels', 'count': 1},
  {'from': 'will133', 'to': 'charris', 'count': 2},
  {'from': 'charris', 'to': 'will133', 'count': 3},
  {'from': 'hmaarrfk', 'to': 'charris', 'count': 2},
  {'from': 'hmaarrfk', 'to': 'eric-wieser', 'count': 2},
  {'from': 'eric-wieser', 'to': 'charris', 'count': 2},
  {'from': 'eric-wieser', 'to': 'hmaarrfk', 'count': 2},
  {'from': 'charris', 'to': 'hmaarrfk', 'count': 3},
  {'from': 'charris', 'to': 'eric-wieser', 'count': 3},
  {'from': 'Sharkoo123', 'to': 'charris', 'count': 3},
  {'from': 'Sharkoo123', 'to': 'seberg', 'count': 3},
  {'from': 'seberg', 'to': 'Sharkoo123', 'count': 4},
  {'from': 'seberg', 'to': 'charris', 'count': 4},
  {'from': 'charris', 'to': 'Sharkoo123', 'count': 1},
  {'from': 'charris', 'to': 'seberg', 'count': 1},
  {'from': 'WarrenWeckesser', 'to': 'pv', 'count': 2},
  {'from': 'WarrenWeckesser', 'to': 'manuels', 'count': 2}]}
# Security Alerts
security_alerts = [
    {
        "type": "Off-hours Access",
        "user": "John Smith",
        "timestamp": (datetime.now() - timedelta(hours=6)).strftime("%Y-%m-%d %H:%M"),
        "severity": "medium",
        "details": "System access detected at 11:45 PM"
    },
    {
        "type": "Multiple Login Attempts",
        "user": "Emma Wilson",
        "timestamp": (datetime.now() - timedelta(days=1)).strftime("%Y-%m-%d %H:%M"),
        "severity": "high",
        "details": "5 failed login attempts detected"
    },
    {
        "type": "Unusual File Access",
        "user": "Michael Chen",
        "timestamp": (datetime.now() - timedelta(hours=12)).strftime("%Y-%m-%d %H:%M"),
        "severity": "low",
        "details": "Accessed restricted project files"
    }
]

# Dashboard Summary
dashboard_summary = {
    "average_performance": 89,
    "total_tasks_completed": 78,
    "active_projects": 12,
    "collaboration_score": 8.5,
    "security_alerts_today": 3,
    "team_productivity_trend": [75, 82, 88, 85, 89, 92, 89],  # Last 7 days
    "department_scores": {
        "Engineering": 87,
        "Design": 90,
        "Product": 88,
        "Analytics": 92
    }
}

